# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Nuget
        uses: warrenbuckley/Setup-Nuget@09c4593220c119ed8d6a811954d72bddd986e29a
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore Nuget package
        run: nuget restore
      - name: MSBuild
        id: msbuild
        run: msbuild /p:Configuration=Release /p:CI=true "./ML in Rhino.sln"
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mlr
          path: ./Components/bin/Release/win-x64
